# Generated by Django 4.2.5 on 2023-10-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "branches",
                "db_table": "branch",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("duration", models.DurationField()),
            ],
            options={
                "verbose_name_plural": "services",
                "db_table": "services",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="profiles.masterprofile",
                    ),
                ),
                ("services", models.ManyToManyField(blank=True, to="salon.service")),
            ],
            options={
                "verbose_name_plural": "service requests",
                "db_table": "service_requests",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="services")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="salon.service"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "service images",
                "db_table": "service_image",
                "ordering": ("-id",),
            },
        ),
    ]
