# Generated by Django 4.2.5 on 2023-10-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name_plural": "client profiles",
                "db_table": "client_profiles",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="MasterProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
                ),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "master profiles",
                "db_table": "master_profiles",
                "ordering": ("-id",),
            },
        ),
    ]
